### ISSUE TITLE
Add device images

### ISSUE THREAD

**Issue by edualm** [FruityRazer/FruityUI-Swift#10]
Most of the device images are missing.

This is easy to add, just fill in the `DeviceImages.plist` file.

The links to the images themselves can be found on Razer’s support page.

**Comment by ukeloop** [comment]
Hi! This project is cool. Assets file path is found on [OpenRazer](https://openrazer.github.io/) project.

**Comment by edualm** [comment]
Closing as we now have a lot of the images thanks to @ukeloop - more should be added over time though.
