### ISSUE TITLE
How do I reset settings?

### ISSUE THREAD

**Issue by ghost** [FruityRazer/FruityUI-Swift#14]
I was fiddling with the settings, and set the number really high, and now fruity UI isn't opening. How to I reset the settings without opening the app?

**Comment by edualm** [comment]
Hey,

There is currently no way to reset the settings (though I'll have to look into that someday).

For now, I think I know what your issue is.

Can you try updating to `1.2.1`? (https://github.com/FruityRazer/FruityUI/releases/v1.2.1)

Thanks!

**Comment by ghost** [comment]
Actually, I just deleted all the fruityui files in the library folder and I erased the settings :)

**Comment by edualm** [comment]
I wasn't sure how that would work because of iCloud Sync, but glad that fixed it.

It shouldn't happen again though! :)
