### ISSUE TITLE
Question: How do you create Synapse 2 effects?

### ISSUE THREAD

**Issue by ghost** [FruityRazer/FruityUI-Swift#15]
Do you grab them from the synapse 2 effect website or do you make them yourself?

**Comment by edualm** [comment]
The Synapse 2 effects are hardware effects, which means that the devices themselves support them. They are special messages sent to the devices (cf. https://github.com/FruityRazer/FruityKit/blob/master/FruityKit/Core/openrazer/razerkbd_driver.c#L320)

Synapse 3 effects are different, and allow for a lot more customization, but there is still only simple support for those on FruityUI. The basis for more advanced effects is already built-in FruityKit though (as you can see, for example, here: https://github.com/FruityRazer/FruityKit/blob/master/FruityKitTests/Synapse3Tests.swift#L14). I plan to eventually add support to FruityUI.
