### ISSUE TITLE
"Static" and "Reactive" doesn't work on Huntsman

### ISSUE THREAD

**Issue by nemosmithasf** [FruityRazer/FruityUI-Swift#17]
Testing with a vanilla Huntsman. All the other effects work, but when I choose "static" and "Reactive" and press save, nothing happens (keyboard stays at the previous effect chosen)

**Comment by edualm** [comment]
Hey @nemosmithasf,

I see what happened there! Can you please try version `1.2.2` (https://github.com/FruityRazer/FruityUI/releases/tag/v1.2.2) and let me know if that fixes your issue?

**Comment by nemosmithasf** [comment]
I'm not quite sure how to compile the code, but I'll definitely check back in once the "consumer" version is released.

**Comment by edualm** [comment]
Oh crap. I forgot to attach the app. 🤦‍♂️

Try again on that same link!

**Comment by nemosmithasf** [comment]
![Screen Shot 2020-07-16 at 12 32 10 PM](https://user-images.githubusercontent.com/14184529/87697679-65630f00-c760-11ea-9f36-708668ff57d1.png)

I get an empty screen with the latest version

**Comment by edualm** [comment]
_sigh_ You're right. I'll need an hour or two before I'm able to work on it, but expect a fixed version in a few hours.

**Comment by edualm** [comment]
Actually, I fixed it.

https://github.com/FruityRazer/FruityUI/releases/tag/v1.2.3

Please give this one a try!

**Comment by nemosmithasf** [comment]
Can confirm that it works now.

Btw, as a side note, I just got the new 60% version (Huntsman Mini) and it does not show up as a recognized device.

If you plan on supporting it, let me know if I can contribute any info.

Thanks for all the good work.

**Comment by edualm** [comment]
Glad to hear that!

Well, I don't know if it supports the same commands as the Huntsman (base/TE/elite), but we can give that a try.

Can you tell me its USB device ID? You can find that info on macOS' system profiler.

https://user-images.githubusercontent.com/387713/68166779-52eecf80-ff5b-11e9-93cc-0407f34eaeb9.png

With that info I can create a build with support for it, though I can't guarantee it'll work without trying first.

**Comment by nemosmithasf** [comment]
No worries, the Huntsman Mini has built-in hardware effects, so I don't think supporting it would be vital. Though if support is already there, it might be worth adding.

The info you asked for:

```
Razer Huntsman Mini:

  Product ID:	0x0257
  Vendor ID:	0x1532
  Version:	2.00
  Serial Number:	00000000001A
  Speed:	Up to 12 Mb/s
  Manufacturer:	Razer
  Location ID:	0x14110000 / 29
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
```

**Comment by edualm** [comment]
Since the Huntsman Mini has built-in hardware effects (which I'm curious about and may eventually get a Huntsman Mini!), it doesn't make sense to add support for hardware-based effects.

I've added support for software-based effects in the last release though.

If you want to give it a try (and check if it works, which I don't even know at this stage!), you can play around with it, feeding it data similar to the data that the Huntsman Elite expects - I think it should be similar (https://github.com/FruityRazer/FruityRazer/wiki/%5BFruityUI%5D-Synapse-3-Configuration-for-Huntsman-Elite).

If you have some time please let me know how that works out! :)

**Comment by nemosmithasf** [comment]
Yeah, for sure. I'll take a look to see if software based effects work as-is in the next version (I can't see the Mini on the sidebar in the current version)

**Comment by edualm** [comment]
Oops, forgot to link to the release!

https://github.com/FruityRazer/FruityUI/releases/tag/v1.2.5

**Comment by nemosmithasf** [comment]
Just tried it, no luck.

The keyboard is recognized but no colours are displayed upon hitting "save". 
Hardware colour switching works as normal with the server running in the background.

**Comment by edualm** [comment]
Well, it was worth a try.

Next step would be analyzing the USB messages that synapse on Windows does, but for that I'd need to own a keyboard. I may eventually... but until then I'm afraid there's not much I can do or try myself.

**Comment by nemosmithasf** [comment]
Thanks again for the good work
