### ISSUE TITLE
app crashes on start

### ISSUE THREAD

**Issue by ashaik4** [FruityRazer/FruityUI-Swift#18]
hardware configuration: razer core x chroma with macbook pro 15 inch 2019. 
[FruityUI_2020-07-17-020431_ashaik.crash.zip](https://github.com/FruityRazer/FruityUI/files/4936232/FruityUI_2020-07-17-020431_ashaik.crash.zip)
attached the crash report here.

**Comment by edualm** [comment]
Hey,

It appears that you attempted to run the app without moving it to the Applications folder, am I right?

Could you try the latest build (https://github.com/FruityRazer/FruityUI/releases/tag/v1.2.5), and running it from the /Applications folder? If it still crashes please send me another crash report and I'll be able to look deeper into it. :)

**Comment by ashaik4** [comment]
Hi @edualm 

I moved the app (build 1.2.5) to the Applications folder. It crashes again. However, it starts fine when I run it without plugging in my eGPU(Razer Core X Chroma).

Also, my razer blackwidow elite keyboard is attached to the USB Port of Razer Core which is connected to my Mac over thunderbolt 3. 
[FruityUI_2020-07-18-145754_ashaik.crash.zip](https://github.com/FruityRazer/FruityUI/files/4942403/FruityUI_2020-07-18-145754_ashaik.crash.zip)

**Comment by edualm** [comment]
![Erm...](https://user-images.githubusercontent.com/387713/87861219-28537400-c93c-11ea-90c4-6ad4d5dc7711.gif)

---

Well, it is probably something related to the hardened runtime, *but* I'm honestly not able to test that. I don't have an eGPU (or, even, a Thunderbolt 3 dock to check if the same problem is present there).

Does it work if you have the eGPU connected but the keyboard connected directly to your Mac?

**Comment by ashaik4** [comment]
nope, it doesn't without eGPU. Everything worked before the latest MacOS update. I think something broke after the MacOS update. 
I am an experienced python developer but I can take a look at the code with some guidance.

**Comment by ashaik4** [comment]
The fruityUI app opens up without any peripherals attached. It doesn't work when any dock, or even when the razer keyboard is attached using a USB to type-c converter.

**Comment by edualm** [comment]
So, I updated my Mac to 10.15.6, and the app still works flawlessly for me.

I have attached a debug build of FruityUI here. Can you try this one? You may need to cmd-click the app to open it as it's not developer ID signed / notarized.

If it still crashes, can you send me the crash log of this one? It should at least give a much clearer message.

[FruityUI.zip](https://github.com/FruityRazer/FruityUI/files/4942998/FruityUI.zip)

**Comment by ashaik4** [comment]
[FruityUI_2020-07-19-011221_ashaik_without_egpu.crash.zip](https://github.com/FruityRazer/FruityUI/files/4943313/FruityUI_2020-07-19-011221_ashaik_without_egpu.crash.zip)
[FruityUI_2020-07-19-011452_ashaik_eGPU.crash.zip](https://github.com/FruityRazer/FruityUI/files/4943316/FruityUI_2020-07-19-011452_ashaik_eGPU.crash.zip)


The app doesn't open with or without eGPU. I have attached the crash reports for both the scenarios.

**Comment by edualm** [comment]
`Exception Type:        EXC_CRASH (Code Signature Invalid)`

Has to do with codesigning, it was signed with my development certificate so it's complaining on your Mac.

Can you try this one, which I've stripped the code signature of? If it doesn't work, I'm afraid you'd have to try compiling it yourself (which isn't hard at all, just requires you to download the developer tools).

[FruityUI No Codesign.zip](https://github.com/FruityRazer/FruityUI/files/4943691/FruityUI.No.Codesign.zip)

**Comment by ashaik4** [comment]
This build worked like a charm. Thank you

**Comment by edualm** [comment]
Only problem with that build is that it's only a workaround, if it worked then it's probably something around sandboxing, but I can't say for sure what.

I guess I can also release debug builds when I release the next versions.

**Comment by RubiRubsn** [comment]
Hi, is there a debug build for the new version? im on a mac mini m1 and the no signed version workes like a charm. however i want to use a firefly v2 and by the version in this thred its not supported yet.
thanks for the nice work ^^

**Comment by edualm** [comment]
@RubiRubsn opened issue #36 related to your comment.
