### ISSUE TITLE
please add Razer Nari Support

### ISSUE THREAD

**Issue by robli314** [FruityRazer/FruityUI-Swift#19]

**Comment by edualm** [comment]
That's a whole different class of devices than what's currently supported, unfortunately.

That would need some USB logs, and someone other than me that owns the device to code that properly.

If someone wants to take this issue, I'd love to get that merged in!

**Comment by robsonliebke** [comment]
I would love to help on that. However, I need some guidance. So, what would be the first step to start on it besides to set the project up on my machine?

**Comment by edualm** [comment]
That's actually not the first step 😅

FruityRazer is based on `openrazer`, so its wiki would be a great place to start. This article is how I added support for some of my devices: https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol

Unfortunately that requires a working Linux install with a Windows VM. :(

Willing to give it a try?
