### ISSUE TITLE
Support for Ornata V2?

### ISSUE THREAD

**Issue by joshuabaird** [FruityRazer/FruityUI-Swift#26]
Is there a chance we will see support for Ornata V2?

**Comment by edualm** [comment]
It should be possible. I'll look into that when I have some time.

**Comment by joshuabaird** [comment]
Thanks, @edualm!

**Comment by edualm** [comment]
Hey @joshuabaird,

This release should work: https://github.com/FruityRazer/FruityUI/releases/tag/v1.2.9

Please let me know if you run into any problems.

**Comment by joshuabaird** [comment]
Thanks!  The device shows as connected now, but no matter the settings, no lights on the keyboard light up:

![image](https://user-images.githubusercontent.com/6271918/105055834-7eb38380-5a41-11eb-816a-8284d1995b86.png)

What am I doing wrong here?

**Comment by joshuabaird** [comment]
Actually - it just started working magically!

**Comment by edualm** [comment]
Glad to hear that!

Unfortunately I can't explain why that might be the cause, but let's hope it stays that way!
