### ISSUE TITLE
Razer Goliathus Extended Chroma

### ISSUE THREAD

**Issue by samuelgomesgit** [FruityRazer/FruityUI-Swift#29]
Hi!

First of all, great job with the app.

Could you please add support for: https://www.razer.com/gaming-mouse-mats/Razer-Goliathus-Chroma/RZ02-02500300-R3M1

Thanks in advance!

**Comment by edualm** [comment]
Hey,

Thanks for your words!

It should be possible. I'll look into that when I have some time. :)

**Comment by edualm** [comment]
Support was added in v1.3.

https://github.com/FruityRazer/FruityUI/releases/tag/v1.3
