### ISSUE TITLE
Add Some Layer

### ISSUE THREAD

**Issue by ahmetolcum** [FruityRazer/FruityUI-Swift#32]
Hi I really appreciate your work, it's a nice designed nicely working app. I only want to ask that is it possible to add some extra layers for the lightning so that we can use multiple layers on our keyboard for example I love using static + reactive layers at the same time. Is it possible to add that kind of a feature. Thank you again for your work and support

**Comment by edualm** [comment]
Hey,

Thanks for your words! :)

As for your request, `FruityKit` (the base framework of FruityUI) has all the pillars set up for that (with regards to Synapse 3 devices) for "custom" animation, but `FruityUI` (the UI part) is not ready for that at all. Additionally, something like Static + Reactive layers would require a lot of per-device investigation, which I do not have either the time or means to do, I am afraid.

Sorry if this answer is not what you were expecting.

If someone has the means/time to implement this, I will be more than happy to merge a pull request with that functionality!

Thanks!
