### ISSUE TITLE
Add Razer Basilisk v2

### ISSUE THREAD

**Issue by LukanoX** [FruityRazer/FruityUI-Swift#33]
Hi,

Any chance of introducing basilisk v2 in the next update? :)

**Comment by edualm** [comment]
Hey,

It should be possible. I'll keep that in mind when I have some time to work on it! :)

**Comment by edualm** [comment]
@LukanoX Please try version `1.4.2` which I just released. Feel free to re-open the issue if it doesn't fix it for you!
