### ISSUE TITLE
Razer Deathadder V2 Pro Wireless

### ISSUE THREAD

**Issue by devantler** [FruityRazer/FruityUI-Swift#34]
I tried connecting the above mouse with the software, and i cant find a profile for it. Are you planning to update FruityUI with support for the mouse? :-)

**Comment by edualm** [comment]
Seems to be possible. I'll take a look as soon as I have some time!

**Comment by edualm** [comment]
@niem94 Please try version `1.4.2` which I just released. Feel free to re-open the issue if it doesn't fix it for you!
