### ISSUE TITLE
Installed the program on my MacOS big sur with razer cynosa lite but cant access the program anymore at all now

### ISSUE THREAD

**Issue by provuser** [FruityRazer/FruityUI-Swift#35]
Entered the app once, tried to shove around with some settings and the color wheel. Ever since i rebooted and tried to enter the FruityUI app i cant get in it. it keeps saying:

Check forupdates automatically?
Then i can press Dont check or Check automatically.

Whatever i press i cannot get in the program. Neiter removing the app from my mac repairs it.
How can i get it to work again and set the keys on the brand new keyboard?

**Comment by edualm** [comment]
Hey @provuser,

That is really weird. The fact that it doesn't appear in the Force Quit menu is *expected* though, as it is considered a menu bar app. Can you get me a full screenshot including the menu bar when the "Check for updates automatically?" window is open?

Anyway - I am afraid FruityUI won't be able to help you in this case, as it currently only has support for lighting effects. It won't be able to help you in remapping keys, unfortunately. 😞 Have you tried software like `BetterTouchTool` (https://folivora.ai/)? It might be able to fix your issue.

**Comment by edualm** [comment]
Closing as this is the same bug as reported in https://github.com/FruityRazer/FruityUI/issues/36.
