### ISSUE TITLE
Mac Mini M1

### ISSUE THREAD

**Issue by edualm** [FruityRazer/FruityUI-Swift#36]
Hi, is there a debug build for the new version? im on a mac mini m1 and the no signed version workes like a charm. however i want to use a firefly v2 and by the version in this thred its not supported yet.
thanks for the nice work ^^

__Originally posted by @RubiRubsn in https://github.com/FruityRazer/FruityUI/issues/18#issuecomment-821801873__

**Comment by edualm** [comment]
Hey,

Can you tell me what the issue is that you're experiencing in your Mac Mini?

I can absolutely get you a debug version in a few hours, but a non-codesigned version is not a permanent fix.

**Comment by RubiRubsn** [comment]
At first i started the signed version and it worked for roundabout 20 seconds, after that it crashed. now when i open the programm it askes me "ckeck for updates automatically?" after that the program crashes again. I tried also the version 1.4.2 , 1.4.1 and 1.3 every one crashes when opening. the only version that workes is the unsigned version.

here a video: 

https://user-images.githubusercontent.com/45696212/115110165-4d801c00-9f7a-11eb-8293-a3cb7425c7c2.mov

**Comment by edualm** [comment]
That's interesting.

Could you let me know if a crash log is generated, and attach it here if possible?

From Apple's docs:

To locate and email crash reports for macOS and Mac Catalyst apps:
Open the Console app, from Applications > Utilities in Finder.
Select Crash Reports.
Locate crash reports for your app in the list. Logs are listed by your app’s binary name.
Right-click the desired log’s file name.
Select Reveal in Finder.

**Comment by RubiRubsn** [comment]
here it is: 
[FruityUI_2021-04-17-121010_Mac-mini-von-Ruben.txt](https://github.com/FruityRazer/FruityUI/files/6329124/FruityUI_2021-04-17-121010_Mac-mini-von-Ruben.txt)

**Comment by RubiRubsn** [comment]
So i tested a bit. 
When my Ornata chroma is not connected the program runs normal. when connecting it crashes instaniously.
is support for the Razer Firefly v2 added? because the firefly isn`t showing up at all.

**Comment by edualm** [comment]
[FruityUI.zip](https://github.com/FruityRazer/FruityUI/files/6329177/FruityUI.zip)

I've attached a non-codesigned, debug build. If this one crashes, could you get me another crash report? It should convey better information than the release one.

As for the Firefly V2, it is not implemented yet but it is ready to be implemented. I'll work on that as soon as I have some time. The linked issue is this one: https://github.com/FruityRazer/FruityKit/issues/17

**Comment by RubiRubsn** [comment]
thx for that ^^
so I tryed it and it works kindof well. when i change the light mode this error pops up: 

```sh
An error has occurred while setting the selected mode.

Maybe this mode isn't supported by your device?
```
But when i press save a second time it works

**Comment by edualm** [comment]
No problem! :)

I have no clue why the debug build works. I'll start releasing debug builds too until I am able to find a solution.

As for the "Save" bug, that may be a quirk on M1 Macs. I don't have an M1 Mac to test the app on but I should get one when the 16" MacBooks are released so let's keep that bug on hold until then.

**Comment by RubiRubsn** [comment]
thanks ^^

**Comment by RubiRubsn** [comment]
With the new Version, the Program works on M1 like a charm :D

**Comment by edualm** [comment]
Glad to hear that! Closing this issue for now, feel free to open a new one if issues persist. :)
