### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by mikeheft** [FruityRazer/FruityUI-Swift#39]
I found [this](https://www.reddit.com/r/MacOS/comments/i1xxzo/how_do_i_install_razer_synapse_3_on_mac_os/g65fse8/) post about installation/usage. But cannot find the FruityUI.app in the project. How does one use this app?

**Comment by edualm** [comment]
Hey,

Just grab the app from here: https://github.com/FruityRazer/FruityUI/releases

**Comment by mikeyduece** [comment]
Sorry, I guess I should've elaborated in my initial post. I've been to that page, but my question still persists. I'm not sure what I'm supposed to DL and/or install out of thos files

**Comment by edualm** [comment]
No worries!

You're supposed to download this one: https://github.com/FruityRazer/FruityUI/releases/download/v1.4.3/FruityUI.zip

Then, just drag it to your `Applications` folder and open. That should be it!

**Comment by edualm** [comment]
For future reference, I've added installation instructions [here](https://github.com/FruityRazer/FruityRazer/wiki/%5BFruityUI%5D-Installation).
