### ISSUE TITLE
Overlap with razer-macos

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [FruityRazer/FruityUI-Swift#42]
https://github.com/1kc/razer-macos/ and this project scope seem to overlap but is is A. unclear what the important differences are and B. likely some duplicated work instead of joining force.

Created a similar issue there too : https://github.com/1kc/razer-macos/issues/386

**Comment by edualm** [comment]
From what I can see, both projects are based in OpenRazer, but the UI is very different - `Razer macOS`'s one is based in Electron, while `FruityUI`'s is based in SwiftUI.

FruityRazer is already separated - there's [FruityKit](https://github.com/FruityRazer/FruityKit) which is the core driver code (and would be the duplicated work), while [FruityUI](https://github.com/FruityRazer/FruityUI) is just the UI.

FruityKit would be a good place to "join forces", but I don't really know how easy it is to use a macOS framework from within Electron.

**Comment by edualm** [comment]
Being discussed [here](https://github.com/1kc/razer-macos/issues/386).
