### ISSUE TITLE
Firefly v2 makes the program crash

### ISSUE THREAD

**Issue by RubiRubsn** [FruityRazer/FruityUI-Swift#44]
Hi, its me again ^^
thanks for adding Firefly V2. But when I´m trying to change a mode on the Firefly FruityUi crashes with no crash report. Also the icon for Firefly is not working.
thx Ruben

**Comment by edualm** [comment]
Hey,

Sorry to hear that. Could you try the debug build, and then check on the `Console` app (`/Applications/Utilities/Console.app`) under `Crash reports` if any report appears there?

Thanks!

**Comment by RubiRubsn** [comment]
Hey, here it is ^^
thx for your help^^
btw is there a way to buy you a coffee? love your app^^
[FruityUI_2021-05-31-094119_Mac-mini-von-Ruben.txt](https://github.com/FruityRazer/FruityUI/files/6568625/FruityUI_2021-05-31-094119_Mac-mini-von-Ruben.txt)

**Comment by edualm** [comment]
Hey,

Thanks for the bug report - that was really useful.

I've published `v1.5.2` that should fix your issue - let me know if not! :)

---

As for the coffee, don't worry about that, I code `FruityRazer` for fun. 
Get yourself a coffee and think about me, that's more than enough! 😄
