### ISSUE TITLE
Speed control not working

### ISSUE THREAD

**Issue by RubiRubsn** [FruityRazer/FruityUI-Swift#45]
Hi, its me again :D 
the speed control of the Wave effect for Firefly V2 is not working :D

**Comment by edualm** [comment]
Hey,

Not-so-good news: the speed control for mouse mats isn't indeed working, but it's not supported by the driver apparently so I'm not going to implement it, at least for now.

I've added some code to conditionally hide that slider if it is not supported for the current device. I am yet to push an update, but the code for that is on the `main` branch already so it will be included in the next update. As of that, I'm marking this issue as done.
