### ISSUE TITLE
Shift and other modifiers not working

### ISSUE THREAD

**Issue by hardtofin** [FruityRazer/FruityUI-Swift#48]
Clicking for example "SHIFT" and "1" on my razer naga trinity does not produce a "!".  Shift is not recognised as a modifier, neither is CTRL or ALT.

This has worked natively in razers software previously (prior to big sur), but does not work in big sur.  I am now using fruity since razer doesnt work at all on big sur but the modifiers don't work in fruity either.

Is this a limitation of big sur or is it possible for modifier keys to work in fruity?

Many thanks.

**Comment by edualm** [comment]
Hey,

That's a weird issue, but it's out of scope for `FruityRazer` unfortunately. All that `FruityRazer` currently does is change stuff related to colors. While that this may change in the future, it's not in our plans right now.

Thanks.
