### ISSUE TITLE
Support for Pro Key and Pro Type

### ISSUE THREAD

**Issue by philipp-adam** [FruityRazer/FruityUI-Swift#57]
Hi,

I've have these devices connected via BT and they show the correct icons in BT (Keyboard and Mice) but are not recognized as such and I can't configure them separately from the internal touchpad (e.g. (non-)natural scrolling.
It would be great if these devices could be supported by this project.

Greets,
Philipp

**Comment by edualm** [comment]
Hey,

FruityUI only supports changing the colors of the devices, at least for now.

Your request is unfortunately out of scope. :(
