### ISSUE TITLE
The Save Button Doesn't Work

### ISSUE THREAD

**Issue by ghost** [FruityRazer/FruityUI-Swift#8]
I have my Blackwidow 2019 and saw the new version, so I got it :) However, although it can recognize my device, the color preferences don't save. Here's a video: https://drive.google.com/file/d/1JJ2s9oqgOIrXJvWeYIvL7xY08otAzta6/view?usp=sharing (GitHUb doesn't let me upload the zip with the video)

**Comment by ghost** [comment]
Oh. wait it works, just had to change to another profile

**Comment by edualm** [comment]
@SangsterMLG What do you mean by "change to another profile"? One of your keyboard profiles? Could be something for me to look into!

**Comment by ghost** [comment]
No, so you know how some keyboards can have multiple stored profiles that can store different light settings and macros? I just had to set it to the default one with the keyboard shortcut, since mine was set to red, although the default is white.

**Comment by edualm** [comment]
Ah I see. That makes sense, thanks for clarifying. :)
